### PR TITLE
add support for Django 2.0 & python 3.6.  remove support for python 3.4 and old django versions

### PR DESCRIPTION
**Pull request by asherf**

### CODE REVIEW

**Comment by hearsaydev** [comment]
[TestStatus] Tests failed

**Comment by asherf** [comment]
@rbm @adepue @jtillman

**Comment by akshayjshah** [comment]
lgtm 🙂

**Comment by akshayjshah** [comment]
As long as we’re making breaking changes, why not drop all the geo support (assuming it’s not used internally)?

**Comment by rbm** [comment]
lgtm, second @akshayjshah (hi Akshay!)

**Comment by akshayjshah** [comment]
👋🏽 Love this blast from the past.

**Comment by rogerhu** [comment]
Hey can I get on this one too.  Hey @akshayjshah

**Comment by asherf** [comment]
we don't use GIS. I removed it. I love deleting stuff :-)

**Pull request merged**
